### ISSUE TITLE
No README.md

### ISSUE THREAD

**Issue by vitosotdihaet** [dodokek/Processor#2]
# No README.md whatsoever.
### I don't want to **_bother_** checking the code to understand the project, so please add a README.md file for the sake of God and my sanity. 😔

#  Here is a TODO list for you, my friend:

- [x] Add README.md

**Comment by dodokek** [comment]
Ok

**Comment by vitosotdihaet** [comment]
# 😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊

**Comment by vitosotdihaet** [comment]
Wait a second
Where the heck is README???????

**Comment by vitosotdihaet** [comment]
UNCLOSE NOW!!!! @dodokek
